### ISSUE TITLE
Make Upcase Open Source

### ISSUE THREAD

**Issue by juandazapata** [thoughtbot/upcase#1679]
This is a great app for people who wants to learn and peek a well coded app. Also handy for people who wants to create their own _online school_. Why not open sourcing it?

Just to clarify, I'm not talking about open sourcing the content (which has way more value IMO), I mean open sourcing the platform.

**Comment by vfonic** [comment]
I don't really understand what are the limitations/permissions of the project's license. It only mentions what happens if you submit a Contribution.

Can anyone elaborate? What happens if you decide to fork and change the codebase, and maybe even publish it as free or commercial product?

Here's the c/p from the [README.md](https://github.com/thoughtbot/upcase/blob/master/README.md#license):

# License

This application is Copyright © 2007 thoughtbot, inc.

If you submit a Contribution to this application's source code, you hereby grant
to thoughtbot, inc. a worldwide, royalty-free, exclusive, perpetual and
irrevocable license, with the right to grant or transfer an unlimited number of
non-exclusive licenses or sublicenses to third parties, under the Copyright
covering the Contribution to use the Contribution by all means, including but
not limited to:

* to publish the Contribution,
* to modify the Contribution, to prepare Derivative Works based upon or
  containing the Contribution and to combine the Contribution with other
  software code,
* to reproduce the Contribution in original or modified form,
* to distribute, to make the Contribution available to the public, display and
  publicly perform the Contribution in original or modified form.

**Comment by tachyons** [comment]
@vfonic That is a grey area, But you can read the code and fork it. You can't redistribute it https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by SViccari** [comment]
Closing this issue as Upcase is now open source 🌟

**Comment by vfonic** [comment]
@SViccari that's great news!

I believe my question is still not answered though. What are the rules/limitations of forking this project and making a webapp out of it? For example if I'd create my own platform "downcase"? What if I wanted to charge for the use of the platform?

The license doesn't cover any of these questions.

I believe this question is extremely important, especially in these days.

Should I open a new issue?

Thanks!

**Comment by tachyons** [comment]
Repository is public, but there is no explicit mention that this project is open source nor a license file is committed to the repo. 

Can you please add a license ?

**Comment by SViccari** [comment]
Hi @vfonic @tachyons - thank you so much for following-up as I misinterpreted "open source" as "public". I'm chatting with the team if we want to remain public or pursue making Upcase open source.  In the interim,  I'll reopen this issue and provide an update as I know more.

**Comment by vfonic** [comment]
Thank you for your efforts @SViccari! Keep us posted! :)

**Comment by vfonic** [comment]
Hey @SViccari!

Thank you for looking into this!
It would save a ton of time if upcase would be truly open source and it would help greatly in these times.

Can you please check with the team and let me know what you decided? 🙏 
Thank you!

**Comment by SViccari** [comment]
@vfonic Thank you for following up. I'm happy to share that adding a license is in progress. https://github.com/thoughtbot/upcase/pull/2230

> It would save a ton of time if Upcase would be truly open source and it would help greatly in these times.

Just out of sheer curiosity, how will open sourcing Upcase "help greatly in these times"?

**Comment by vfonic** [comment]
Thanks for asking! It's a learning platform that can be used to...well...build learning platform(s).

And today, when everything suddenly moved online, it could be of great help for so many people:
- people willing to learn online
- people willing to offer teaching online
- companies giving seminars / workshops online
- ...

**Comment by mjankowski** [comment]
We just merged in the MIT license update.
